### ISSUE TITLE
http-auth可以设置不同的账号并为不同账号设置权限吗？

### ISSUE THREAD

**Issue by Jimmylee0420** [codeskyblue/gohttpserver#111]

**Comment by codeskyblue** [comment]
可以直接在`.ghs.yml` 中配置的

**Comment by Jimmylee0420** [comment]
> 可以直接在`.ghs.yml` 中配置的

有具体示例不？现在我想给不同的账号设置不同的密码和权限？

**Comment by codeskyblue** [comment]
文档里面有写的。
```yaml
---
upload: false
delete: false
users:
- email: "codeskyblue@codeskyblue.com"
  delete: true
  upload: true
  token: 4567gf8asydhf293r23r
```
