### ISSUE TITLE
目录下存在 .uploadable的文件，允许上传

### ISSUE THREAD

**Issue by codeskyblue** [codeskyblue/gohttpserver#2]
```
- foo/
- bar/
    `-- .uploadable
```

**Comment by codeskyblue** [comment]
`.ghs.yml` 文件名，以后可能会涉及到登录用户, 添加了upload，默认就是全部允许

```yaml
upload: true
upload-allow:
- codeskyblue
```
