### ISSUE TITLE
is there a docker compose sample?

### ISSUE THREAD

**Issue by aniel300** [codeskyblue/gohttpserver#220]
is there a docker compose sample?

**Comment by Feyico** [comment]
my example
```
version: '3'
services:
  gohttpserver:
    image: gohttpserver:latest
    container_name: gohttpserver
    network_mode: bridge
    ports:
    - 8080:8000
    restart: always
    volumes:
    - '/opt/data/repo-data/:/mnt'
```
